name: Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.*/**'
      - '**/*.md'

env:
  IMAGE_REPO: paulsmithcruk
  IMAGE_NAME: youtube-dl

jobs:
  Push-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure updater for bleeding-edge yt-dlp
        run: |
          sed -i -E '6s!.*!pip --no-cache-dir --quiet install --upgrade --force-reinstall --no-deps git+https://github.com/yt-dlp/yt-dlp.git!i' 'root/app/youtube-dl/updater.sh'

      - name: Add git
        run: |
          sed -i -E 's!(python3-pip)!\1 git!i' Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest
